# Start with a base image that includes OpenJDK
FROM openjdk:17-jdk-alpine

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8081 available to the world outside this container
EXPOSE 8081

# The application's jar file
ARG JAR_FILE=target/upi-payment-service-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} upi-payment-service.jar

# Run the jar file
ENTRYPOINT ["java","-jar","/upi-payment-service.jar"]
